#!/usr/bin/with-contenv bash

# 创建文件夹
#	mkdir -p \
#	/config

# 映射配置目录
	ln -s /root/.ccnet /config/ccnet

# 授权
	chown -R abc:abc \
		/config \
		/seafile-data
	chmod -R g+w \
		/config \
		/seafile-data