#!/usr/bin/with-contenv bash

# 将abc用户添加到root/sudo用户组
# usermod -g root,sudo abc
# echo "Add abc to ROOT"
# 经验证，此方法不能解决文件映射的权限问题，以此留证。

# 配置权限，sf为数据目录，app为配置目录
chown -R abc:abc \
	/app \
	/config
chmod -R g+w \
	/app \
	/config
