#!/usr/bin/with-contenv bash

# 映射配置目录
# 第一条用于容器启动时直接读取ccnet配置
# ln -s /app/ccnet /config/.ccnet
# 第二条用于后台使用时直接查看状态
ln -s /app/ccnet /root/.ccnet

# 输出当前时间
echo "-------------------------------------"
echo "                                     "
echo “TIME：$(date)”
echo "                                     "
echo "-------------------------------------"

# 使用abc用户启动软件，seafile程序生成的文件权限为abc:abc
# 如果直接启动，将导致seafile程序生成的文件权限为root:root
# 如下方式终于可以完美实现docker正常启动、seafile文件权限也正确。
echo "                                     "
runuser -u abc -g abc /usr/bin/seaf-cli start -c /app/ccnet
echo "                                     "
echo "-------------------------------------"
echo "                                     "
echo "seafile started                      "
echo "                                     "
echo "-------------------------------------"
