#!/usr/bin/with-contenv bash

# 映射配置目录
 ln -s /app/ccnet /config/.ccnet

# 更改用户
# su abc

# 输出当前时间
echo "-------------------------------------"
echo "                                     "
echo “TIME：$(date)”
echo "                                     "
echo "-------------------------------------"

# 启动软件
echo "                                     "
runuser -u abc -g abc /usr/bin/seaf-cli start
echo "                                     "
echo "-------------------------------------"
echo "                                     "
echo "seafile started                      "
echo "                                     "
echo "-------------------------------------"
